
package com.succez.custom.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-07-21T09:49:56.733+08:00
 * Generated source version: 2.7.7
 * 
 */
public final class SMSWebServiceSoap_SMSWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "SMSWebService");

    private SMSWebServiceSoap_SMSWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SMSWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SMSWebService ss = new SMSWebService(wsdlURL, SERVICE_NAME);
        SMSWebServiceSoap port = ss.getSMSWebServiceSoap();  
        
        {
        System.out.println("Invoking sendTimeMessage...");
        java.lang.String _sendTimeMessage_smsTime = "";
        java.lang.String _sendTimeMessage_smsContent = "";
        java.lang.String _sendTimeMessage_phoneNumber = "";
        java.lang.String _sendTimeMessage__return = port.sendTimeMessage(_sendTimeMessage_smsTime, _sendTimeMessage_smsContent, _sendTimeMessage_phoneNumber);
        System.out.println("sendTimeMessage.result=" + _sendTimeMessage__return);


        }
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_smsContent = "";
        java.lang.String _sendMessage_phoneNumber = "";
        int _sendMessage_phoneNumberType = 0;
        java.lang.String _sendMessage__return = port.sendMessage(_sendMessage_smsContent, _sendMessage_phoneNumber, _sendMessage_phoneNumberType);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }

        System.exit(0);
    }

}
