Create Or Replace View F_CONTRACT_INFO1 As 

SELECT T.ZHRMBJE AS CONTRACT_MONEY_RMB,
			 T."UID" AS ID,
			 '' AS STATE_ID,
			 T.CONT_SUB_TYPE As CONT_TYPE_ID,
       t.cont_id As CONTRACT_CODE,
       t.cont_name As CONTRACT_NAME,
       t.org  As  CREATE_ORG_SEQ,
       t.curr_id As MONEY_TYPE_ID,
       t.money_in_out As MONEY_INOUT_ID,
       '' As OUR_SIGNER,
       t.money_type As CONT_MONEY_TYPE_ID,
       t.Createtime As CREATETIME,
       t.RATE As RATE,
       '' As OPPOSITE_SIGNER,
       '' As CONTRACT_SIGNED_DATE,
       t.cont_num As CONTRACT_NUM
	FROM LC_LC_CONTRACTINFO T;
  
  COMMENT ON COLUMN F_CONTRACT_INFO1.CONTRACT_MONEY_RMB IS '合同金额折合人民币';
COMMENT ON COLUMN F_CONTRACT_INFO1.ID IS '合同号';
COMMENT ON COLUMN F_CONTRACT_INFO1.STATE_ID IS '合同状态';
COMMENT ON COLUMN F_CONTRACT_INFO1.CONT_TYPE_ID IS '合同类别';
COMMENT ON COLUMN F_CONTRACT_INFO1.CONTRACT_CODE IS '合同编号';
COMMENT ON COLUMN F_CONTRACT_INFO1.CONTRACT_NAME IS '合同名称';
COMMENT ON COLUMN F_CONTRACT_INFO1.CREATE_ORG_SEQ IS '经办单位';
COMMENT ON COLUMN F_CONTRACT_INFO1.MONEY_TYPE_ID IS '币种ID';
COMMENT ON COLUMN F_CONTRACT_INFO1.MONEY_INOUT_ID IS '资金流向ID';
COMMENT ON COLUMN F_CONTRACT_INFO1.OUR_SIGNER IS '我方签约人名称';
COMMENT ON COLUMN F_CONTRACT_INFO1.CONT_MONEY_TYPE_ID IS '金额类型ID';
COMMENT ON COLUMN F_CONTRACT_INFO1.CREATETIME IS '经办时间';
  COMMENT ON COLUMN F_CONTRACT_INFO1.RATE IS '汇率';
  COMMENT ON COLUMN F_CONTRACT_INFO1.OPPOSITE_SIGNER IS '对方签约人名称';
COMMENT ON COLUMN F_CONTRACT_INFO1.CONTRACT_SIGNED_DATE IS '合同签订日期';
COMMENT ON COLUMN F_CONTRACT_INFO1.CONTRACT_NUM IS '合同工号';


  
